version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - .:/app
    command: sh -c "exec uvicorn main:app --host 0.0.0.0 --port 8080 --reload"