services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: abx_test
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["./scripts/wait-for-db.sh", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  db_data: